"""
Django settings for sahayak project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&e6=p^m+)7%j+cty81)jfsz!m)11z*h2alryukx7g7n1g+!61^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'doctor.apps.DoctorConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sahayak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sahayak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# added manually
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'testhamza53@gmail.com'
EMAIL_HOST_PASSWORD = 'drfy gawc ngeb tpao'


MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# maneging media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCMbIq6mOGEVzL+
E+pK/aP60tMn17rny3JmDokGkzuIF8SyQNh9OZvByMVEdMit8Id7Rgrw37CHQ3wx
rykrj+LvjtZ/7AqZuG7BmZoDJE3/wPl/BHELWtFjz+fj9IsGxjZq3WLAdOVFYQ4h
JfEqoWQH5hVxv8XAVkwrfaRsYK+4M5hDqresREaxx2RkqEEClLdpqumBuxuHZB9m
l32Bs21tRcUyjspSZst2LaxHCAFXgw2BZ6pjDp5fwcPMS14nI9n5EDTjy3Xxwy6i
lJKXqcv8QeYYFK3Rc/DUqcFwWVBAlsdhTq/qqHQ6N4zbMkKQQQh5F6tqukiZFDFe
PneJ+TzLAgMBAAECggEAKg5oDjKzeBtVnlsAlK0aa4iwzQIDbGC2RnKb/2ghMEVO
F8TsEbUrPQKQckw3vkCHkxgLNtEH4bsIeyjmv7E8WlsBSxa6pgdixIDoa4B4C90T
3ELMSIZOqAIghVk8Oi8rJR5g8RsRf5Ht1WezrvzfJK54RbUV2OD/txbOI9dhSV1Y
7gV+Fnx38lTQ0iJ9ksqUJc44q7cw2Bvx4MO8PctYPmqPsrnZGbYz0AL1DmFMfZoJ
dXwiD/FjL4O2VuWT6OCxEABEPbRGeZmwbHHPMex0tMFnR9Iz9+fdQ20qzd3IC5Xv
LaONWeaY6DWs8yjFHe7gIUAjh1AnrinjPCbTTtfxQQKBgQC/F8H9NrhRzskt0Xgt
ZLIhm5P3XOFKmhDV8GKs4/Ja0A+twSwGtEkS7qWKUEDmTd1l3K5LfmOjrd6uegU1
NYWA0pEQUc0qGfjazhx7wsvq2xIoG+EJKTLNkW0bJrXDOeyHA+uuaDuUDkD/fHJv
M/6v2BY3mDkB5x9hGvIAinLN+QKBgQC8HvByuaXagQ8t+wQMc+LOxSM5zP9sdL/T
3EhdnN9oxs6BfQ1CWF+XlL817YNMgnDRiuEGrBH5lmhaueKvxa7pwfJvq393vvSB
w6QgLGnEG2uUwS19Zcqkwj10h5wQymHoQS3bgq/TZ9IsoqcX4ILaosalcYY+1t9a
b4MlfHuh4wKBgHtYHHETJvo3HYgjkwzJ2Gj1ARdDrm/27jMJjMfIAqE3d0dSTtas
/BXqUJPspVeCnwum3CICnNID4p6ASGhF+bxjLht4kZNBXG3vaFdCL1mSui+Ff0Xo
f9BMtD44SE6RTuj/UNsskHhKkw3WCA9bYmOieQS9jt55jrmhKN/MfboRAoGAXy8o
amQUzyJOE+3WdpaMRCLrV+upsa7BAOmMlBEz2Uf+ZPZpJxCgDYpt1VOAA85cVyn2
AfI+hhLcaktzr4xOnGhNysLzlBtCjAX5nW3bdiaJoJK9+Zzvk73UaonTJYvBTkrs
cQ0G+eimJ3+FHEe07fs+l6eBTXpbON8DdIwv4hECgYEAtc+7p+Xp1cPxLXWmJhH2
y5vek7K5QUkKrDOL8iQ7n3AcJQNdzJNbuEFLIHjtzygTe0ZE9dsvjCEbElC8wiZl
cwmIJDvuOhI1JVhMtRm4s/WtEXkobbYfjUoMyv2Z1DLGnTxPWhCdl5XoGCVxOSDB
6IXHzzWbzxdIoaDPOTOv0mk=
-----END PRIVATE KEY-----"""




# Load Auth0 application settings into memory

AUTH0_DOMAIN = "dev-fpt07fwefmgitl8v.us.auth0.com"
AUTH0_CLIENT_ID = "aXn1lek5XNpNSAEbAeIQ2tfYfXimmCgW"
AUTH0_CLIENT_SECRET = "YfFHAz3I1vkgGhCfN4rYJHEGAlebX1YBEfqhJQQKrED6ns_PuknHjKXlXwCn86oz"



# MongoDB Atlas credentials
MONGODB_USER = 'hackthemountain'
MONGODB_PASSWORD = '1@Qwertyuiop'
MONGODB_CLUSTER_URL = 'cluster0.0vqiy.mongodb.net'