# Generated by Django 3.2.7 on 2024-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_link', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Sessiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('join_link', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('lname', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('user_u_no', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=60)),
                ('address', models.TextField()),
            ],
        ),
    ]
